# name of our workflow
name: Django CI/CD Workflow

# triggers for our workflow
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  SQL_DATABASE: sampleapp
  SQL_USER: postgres
  SQL_PASSWORD: postgres
  SQL_HOST: localhost
  SQL_PORT: 5432
  SQL_ENGINE: django.db.backends.postgresql

jobs:
  run_tests:
    name: Run Django Tests
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: sampleapp
        ports:
          - 5432:5432
        options: --mount type=tmpfs,destination=/var/lib/postgresql/data --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest -vv
        env:
          SYSTEM_ENV: GITHUB_WORKFLOW
